/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.lcp.view;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author Unesp07
 */
public class formPrincipal extends javax.swing.JFrame {
    JDesktopPane jdDesktop;
    
    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
        jdDesktop = new JDesktopPane();
        setContentPane(jdDesktop);
	jdDesktop.putClientProperty("JDesktopPane.dragMode", "outline");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenu1 = new javax.swing.JMenu();
    jPopupMenu1 = new javax.swing.JPopupMenu();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuBar2 = new javax.swing.JMenuBar();
    jMenu6 = new javax.swing.JMenu();
    jMenu7 = new javax.swing.JMenu();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenu5 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenu8 = new javax.swing.JMenu();

    jMenu1.setText("jMenu1");

    jMenuItem5.setText("jMenuItem5");

    jMenu6.setText("File");
    jMenuBar2.add(jMenu6);

    jMenu7.setText("Edit");
    jMenuBar2.add(jMenu7);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jMenu2.setText("Produto");

    jMenuItem3.setText("Cadastro");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem3);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Cliente");

    jMenuItem4.setText("Cadastro");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu5.setText("Admin");

    jMenuItem1.setText("Cadastro");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu5.add(jMenuItem1);

    jMenuBar1.add(jMenu5);

    jMenu4.setText("Venda");

    jMenuItem2.setText("Efetuar");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu4.add(jMenuItem2);

    jMenuBar1.add(jMenu4);

    jMenu8.setLabel("Sair");
    jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMenu8MouseClicked(evt);
      }
    });
    jMenu8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenu8ActionPerformed(evt);
      }
    });
    jMenuBar1.add(jMenu8);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1062, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 584, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        cadastroProduto cp = new cadastroProduto();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cp.getSize();
        cp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cp.setVisible(true);
        jdDesktop.add(cp);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        cadastroCliente cc = new cadastroCliente();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cc.getSize();
        cc.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cc.setVisible(true);
        jdDesktop.add(cc);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CadastroUsuario cadU = new CadastroUsuario();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cadU.getSize();
        cadU.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cadU.setVisible(true);
        jdDesktop.add(cadU);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormVenda fv = new FormVenda();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = fv.getSize();
        fv.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        fv.setVisible(true);
        jdDesktop.add(fv);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
    
  }//GEN-LAST:event_jMenu8ActionPerformed

  private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
    this.setVisible(false);
    
    Application ap = new Application();
    ap.setVisible(true);
  }//GEN-LAST:event_jMenu8MouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu7;
  private javax.swing.JMenu jMenu8;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuBar jMenuBar2;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JPopupMenu jPopupMenu1;
  // End of variables declaration//GEN-END:variables
}
